# Generated by Django 3.2.10 on 2022-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserQuizzes', '0003_alter_quizzes_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='no_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
